//

// roomAction types

export const INIT_ROOM_FETCHING = 'INIT_ROOM_FETCHING'
export const INIT_ROOM_SUCCESS = 'INIT_ROOM_SUCCESS'
export const INIT_ROOM_FAILURE = 'INIT_ROOM_FAILURE'

export const MOVE_ROOM_FETCHING = 'MOVE_ROOM_FETCHING'
export const MOVE_ROOM_SUCCESS = 'MOVE_ROOM_SUCCESS'
export const MOVE_ROOM_FAILURE = 'MOVE_ROOM_FAILURE'

export const GET_ITEM_FETCHING = 'GET_ITEM_FETCHING'
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE'


// playerAction types
export const INIT_PLAYER_FETCHING = 'INIT_PLAYER_FETCHING'
export const INIT_PLAYER_SUCCESS = 'INIT_PLAYER_SUCCESS'
export const INIT_PLAYER_FAILURE = 'INIT_PLAYER_FAILURE'


export const SELL_ITEM_FETCHING = 'SELL_ITEM_FETCHING'
export const SELL_ITEM_SUCCESS = 'SELL_ITEM_SUCCESS'
export const SELL_ITEM_FAILURE = 'SELL_ITEM_FAILURE'